#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-coveralls
Version  : 0.8.1
Release  : 3
URL      : https://rubygems.org/downloads/coveralls-0.8.1.gem
Source0  : https://rubygems.org/downloads/coveralls-0.8.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-coveralls-bin
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
# [Coveralls](http://coveralls.io) for Ruby [![Test Coverage](https://coveralls.io/repos/lemurheavy/coveralls-ruby/badge.svg?branch=master)](https://coveralls.io/r/lemurheavy/coveralls-ruby) [![Build Status](https://secure.travis-ci.org/lemurheavy/coveralls-ruby.svg?branch=master)](https://travis-ci.org/lemurheavy/coveralls-ruby) [![Gem Version](https://badge.fury.io/rb/coveralls.svg)](http://badge.fury.io/rb/coveralls)

%package bin
Summary: bin components for the rubygem-coveralls package.
Group: Binaries

%description bin
bin components for the rubygem-coveralls package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n coveralls-0.8.1
gem spec %{SOURCE0} -l --ruby > rubygem-coveralls.gemspec

%build
gem build rubygem-coveralls.gemspec

%install
gem_dir=$(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .${gem_dir} \
--bindir .%{_bindir} \
coveralls-0.8.1.gem

mkdir -p %{buildroot}${gem_dir}
cp -pa .${gem_dir}/* \
%{buildroot}${gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/coveralls-0.8.1.gem
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/API/apified_hash-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/API/cdesc-API.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/API/disable_net_blockers%21-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/API/endpoint_to_url-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/API/hash_to_file-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/API/post_json-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/CommandLine/cdesc-CommandLine.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/CommandLine/ensure_can_run_locally%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/CommandLine/last-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/CommandLine/open-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/CommandLine/open_token_based_url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/CommandLine/push-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/CommandLine/report-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/CommandLine/service-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/CommandLine/version-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/Configuration/cdesc-Configuration.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/Configuration/configuration-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/Configuration/configuration_path-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/Configuration/git-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/Configuration/pwd-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/Configuration/rails_root-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/Configuration/relevant_env-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/Configuration/root-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/Configuration/set_service_params_for_appveyor-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/Configuration/set_service_params_for_circleci-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/Configuration/set_service_params_for_coveralls_local-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/Configuration/set_service_params_for_jenkins-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/Configuration/set_service_params_for_semaphore-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/Configuration/set_service_params_for_tddium-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/Configuration/set_service_params_for_travis-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/Configuration/set_standard_service_params_for_generic_ci-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/Configuration/simplecov_root-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/Configuration/yaml_config-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/NilFormatter/cdesc-NilFormatter.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/NilFormatter/format-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/Output/cdesc-Output.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/Output/format-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/Output/no_color%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/Output/no_color-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/Output/output-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/Output/print-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/Output/puts-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/Output/silent%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/Output/silent-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/RakeTask/Rake/cdesc-Rake.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/RakeTask/cdesc-RakeTask.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/RakeTask/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/SimpleCov/Formatter/cdesc-Formatter.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/SimpleCov/Formatter/display_error-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/SimpleCov/Formatter/display_result-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/SimpleCov/Formatter/format-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/SimpleCov/Formatter/output_message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/SimpleCov/Formatter/short_filename-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/SimpleCov/cdesc-SimpleCov.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/cdesc-Coveralls.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/noisy%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/noisy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/push%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/run_locally-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/setup%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/should_run%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/start%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/testing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/wear%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/wear_merged%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/Coveralls/will_run%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/coveralls-0.8.1/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/coveralls-0.8.1/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/coveralls-0.8.1/.rspec
/usr/lib64/ruby/gems/2.2.0/gems/coveralls-0.8.1/.travis.yml
/usr/lib64/ruby/gems/2.2.0/gems/coveralls-0.8.1/CHANGELOG.md
/usr/lib64/ruby/gems/2.2.0/gems/coveralls-0.8.1/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/coveralls-0.8.1/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/coveralls-0.8.1/README.md
/usr/lib64/ruby/gems/2.2.0/gems/coveralls-0.8.1/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/coveralls-0.8.1/bin/coveralls
/usr/lib64/ruby/gems/2.2.0/gems/coveralls-0.8.1/coveralls-ruby.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/coveralls-0.8.1/lib/coveralls.rb
/usr/lib64/ruby/gems/2.2.0/gems/coveralls-0.8.1/lib/coveralls/api.rb
/usr/lib64/ruby/gems/2.2.0/gems/coveralls-0.8.1/lib/coveralls/command.rb
/usr/lib64/ruby/gems/2.2.0/gems/coveralls-0.8.1/lib/coveralls/configuration.rb
/usr/lib64/ruby/gems/2.2.0/gems/coveralls-0.8.1/lib/coveralls/output.rb
/usr/lib64/ruby/gems/2.2.0/gems/coveralls-0.8.1/lib/coveralls/rake/task.rb
/usr/lib64/ruby/gems/2.2.0/gems/coveralls-0.8.1/lib/coveralls/simplecov.rb
/usr/lib64/ruby/gems/2.2.0/gems/coveralls-0.8.1/lib/coveralls/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/coveralls-0.8.1/spec/coveralls/configuration_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/coveralls-0.8.1/spec/coveralls/coveralls_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/coveralls-0.8.1/spec/coveralls/fixtures/app/controllers/sample.rb
/usr/lib64/ruby/gems/2.2.0/gems/coveralls-0.8.1/spec/coveralls/fixtures/app/models/airplane.rb
/usr/lib64/ruby/gems/2.2.0/gems/coveralls-0.8.1/spec/coveralls/fixtures/app/models/dog.rb
/usr/lib64/ruby/gems/2.2.0/gems/coveralls-0.8.1/spec/coveralls/fixtures/app/models/house.rb
/usr/lib64/ruby/gems/2.2.0/gems/coveralls-0.8.1/spec/coveralls/fixtures/app/models/robot.rb
/usr/lib64/ruby/gems/2.2.0/gems/coveralls-0.8.1/spec/coveralls/fixtures/app/models/user.rb
/usr/lib64/ruby/gems/2.2.0/gems/coveralls-0.8.1/spec/coveralls/fixtures/app/vendor/vendored_gem.rb
/usr/lib64/ruby/gems/2.2.0/gems/coveralls-0.8.1/spec/coveralls/fixtures/sample.rb
/usr/lib64/ruby/gems/2.2.0/gems/coveralls-0.8.1/spec/coveralls/output_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/coveralls-0.8.1/spec/coveralls/simplecov_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/coveralls-0.8.1/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/specifications/coveralls-0.8.1.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/coveralls
